/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/generate-calc-index.mjs
 */

export interface CalculatorIndexItem {
    id: string;
    name: string;
}

export const ALL_CALCULATORS: CalculatorIndexItem[] = [
    {
        "id": "age",
        "name": "Age Calculator"
    },
    {
        "id": "bmi",
        "name": "BMI Calculator"
    },
    {
        "id": "body-fat",
        "name": "Body Fat Calculator"
    },
    {
        "id": "calorie",
        "name": "Calorie Calculator"
    },
    {
        "id": "compound-interest",
        "name": "2026 Compound Interest Calculator | Wealth Accretion Engine"
    },
    {
        "id": "conversion",
        "name": "Unit Conversion Calculator"
    },
    {
        "id": "date",
        "name": "Date Calculator"
    },
    {
        "id": "home-afford",
        "name": "Home Affordability Calculator"
    },
    {
        "id": "loan",
        "name": "Loan Calculator"
    },
    {
        "id": "mortgage",
        "name": "Mortgage Calculator"
    },
    {
        "id": "ovulation",
        "name": "Ovulation Calculator"
    },
    {
        "id": "percentage",
        "name": "Percentage Calculator"
    },
    {
        "id": "pregnancy",
        "name": "Pregnancy Calculator"
    },
    {
        "id": "refinance",
        "name": "Refinance Calculator"
    },
    {
        "id": "scientific",
        "name": "Scientific Calculator"
    },
    {
        "id": "self-employment",
        "name": "Self Employment Tax Calculator"
    },
    {
        "id": "tax",
        "name": "Tax Calculator"
    },
    {
        "id": "time-calculator",
        "name": "Time Calculator"
    },
    {
        "id": "tip",
        "name": "2026 Tip Calculator | Gratuity Gold Precision Engine"
    },
    {
        "id": "workers-comp",
        "name": "Workers Comp Calculator"
    }
];
