/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/generate-calc-index.mjs
 */

export interface CalculatorIndexItem {
    id: string;
    name: string;
}

export const ALL_CALCULATORS: CalculatorIndexItem[] = [
    {
        "id": "1099-tax",
        "name": "1099 Tax Calculator"
    },
    {
        "id": "18-wheeler",
        "name": "18 Wheeler Accident Calculator"
    },
    {
        "id": "3m-earplug",
        "name": "3M Earplug Settlement Calculator"
    },
    {
        "id": "401k-growth",
        "name": "401k-growth"
    },
    {
        "id": "529",
        "name": "529 Plan Calculator"
    },
    {
        "id": "abilify",
        "name": "Abilify Lawsuit Calculator"
    },
    {
        "id": "accutane",
        "name": "Accutane Side Effects Calculator"
    },
    {
        "id": "afff",
        "name": "AFFF Lawsuit Calculator"
    },
    {
        "id": "age",
        "name": "Age Calculator"
    },
    {
        "id": "airbnb-income",
        "name": "Airbnb Income Calculator"
    },
    {
        "id": "alimony",
        "name": "Alimony Calculator"
    },
    {
        "id": "amusement-park",
        "name": "Amusement Park Injury Calculator"
    },
    {
        "id": "ankle-implant",
        "name": "Ankle Implant Lawsuit Calculator"
    },
    {
        "id": "annuity",
        "name": "Annuity Calculator"
    },
    {
        "id": "antique-car-insurance",
        "name": "Antique Car Insurance Calculator"
    },
    {
        "id": "art-insurance",
        "name": "Art Insurance Calculator"
    },
    {
        "id": "asbestos",
        "name": "Asbestos Exposure Calculator"
    },
    {
        "id": "atrium-mesh",
        "name": "Atrium C-Qur Mesh Calculator"
    },
    {
        "id": "atv-accident",
        "name": "ATV Accident Calculator"
    },
    {
        "id": "atv-insurance",
        "name": "ATV Insurance Calculator"
    },
    {
        "id": "auto-insurance",
        "name": "Auto Insurance Calculator"
    },
    {
        "id": "aviation",
        "name": "Aviation Accident Calculator"
    },
    {
        "id": "baby-formula",
        "name": "NEC Baby Formula Settlement Calculator"
    },
    {
        "id": "bail-bond",
        "name": "Bail Bond Calculator"
    },
    {
        "id": "bair-hugger",
        "name": "Bair Hugger Lawsuit Calculator"
    },
    {
        "id": "bar-insurance",
        "name": "Bar Insurance Calculator"
    },
    {
        "id": "bard-mesh",
        "name": "Bard Hernia Mesh Calculator"
    },
    {
        "id": "bard-powerport",
        "name": "Bard PowerPort Lawsuit Calculator"
    },
    {
        "id": "benzene",
        "name": "Benzene Leukemia Calculator"
    },
    {
        "id": "binary",
        "name": "Binary Calculator"
    },
    {
        "id": "biomet-hip",
        "name": "Biomet Hip Lawsuit Calculator"
    },
    {
        "id": "birth-injury",
        "name": "Birth Injury Settlement Calculator"
    },
    {
        "id": "black-lung",
        "name": "Black Lung Settlement Calculator"
    },
    {
        "id": "bmi",
        "name": "BMI Calculator"
    },
    {
        "id": "boat-insurance",
        "name": "Boat Insurance Calculator"
    },
    {
        "id": "boating-accident",
        "name": "Boating Accident Calculator"
    },
    {
        "id": "body-fat",
        "name": "Body Fat Calculator"
    },
    {
        "id": "bone-graft",
        "name": "Bone Graft Lawsuit Calculator"
    },
    {
        "id": "bonus-tax",
        "name": "Bonus Tax Calculator"
    },
    {
        "id": "breast-implant",
        "name": "Breast Implant Illness Calculator"
    },
    {
        "id": "burn-injury",
        "name": "Burn Injury Calculator"
    },
    {
        "id": "bus-accident",
        "name": "Bus Accident Calculator"
    },
    {
        "id": "business-insurance",
        "name": "Business Insurance Cost Calculator"
    },
    {
        "id": "calorie",
        "name": "Calorie Calculator"
    },
    {
        "id": "camp-lejeune",
        "name": "Camp Lejeune Settlement Calculator"
    },
    {
        "id": "camper-insurance",
        "name": "Camper Insurance Calculator"
    },
    {
        "id": "capital-gains",
        "name": "Capital Gains Tax Calculator"
    },
    {
        "id": "car-accident",
        "name": "car-accident"
    },
    {
        "id": "casino-injury",
        "name": "Casino Injury Calculator"
    },
    {
        "id": "charitable-donation",
        "name": "Charitable Donation Calculator"
    },
    {
        "id": "chemical-burn",
        "name": "Chemical Burn Calculator"
    },
    {
        "id": "child-care-subsidy",
        "name": "Child Care Subsidy Calculator"
    },
    {
        "id": "child-support",
        "name": "Child Support Calculator"
    },
    {
        "id": "classic-car-insurance",
        "name": "Classic Car Insurance Calculator"
    },
    {
        "id": "closing-cost",
        "name": "Closing Cost Calculator"
    },
    {
        "id": "collectible-insurance",
        "name": "Collectible Insurance Calculator"
    },
    {
        "id": "commercial-auto",
        "name": "Commercial Auto Calculator"
    },
    {
        "id": "commercial-insurance",
        "name": "Commercial Insurance Calculator"
    },
    {
        "id": "commercial-vehicle",
        "name": "Commercial Vehicle Accident Calculator"
    },
    {
        "id": "commission",
        "name": "Commission Calculator"
    },
    {
        "id": "compound-interest",
        "name": "2026 Compound Interest Calculator | Wealth Accretion Engine"
    },
    {
        "id": "concert-injury",
        "name": "Concert Injury Calculator"
    },
    {
        "id": "condo-insurance",
        "name": "Condo Insurance Calculator"
    },
    {
        "id": "construction-accident",
        "name": "Construction Accident Settlement Calculator"
    },
    {
        "id": "contractor-insurance",
        "name": "Contractor Insurance Calculator"
    },
    {
        "id": "conversion",
        "name": "Unit Conversion Calculator"
    },
    {
        "id": "cpap",
        "name": "CPAP Recall Lawsuit Calculator"
    },
    {
        "id": "crane",
        "name": "Crane Injury Calculator"
    },
    {
        "id": "crossfit-injury",
        "name": "CrossFit Injury Calculator"
    },
    {
        "id": "crowd-crush",
        "name": "Crowd Crush Calculator"
    },
    {
        "id": "cruise-insurance",
        "name": "Cruise Insurance Calculator"
    },
    {
        "id": "crypto-tax",
        "name": "Crypto Tax Calculator"
    },
    {
        "id": "cyber-insurance",
        "name": "Cyber Insurance Calculator"
    },
    {
        "id": "date",
        "name": "Date Calculator"
    },
    {
        "id": "daycare-injury",
        "name": "Daycare Injury Calculator"
    },
    {
        "id": "daycare-insurance",
        "name": "Daycare Insurance Calculator"
    },
    {
        "id": "delivery-insurance",
        "name": "Delivery Driver Insurance Calculator"
    },
    {
        "id": "dental-insurance",
        "name": "Dental Insurance Calculator"
    },
    {
        "id": "depo-provera",
        "name": "Depo-Provera Lawsuit Calculator"
    },
    {
        "id": "depuy-hip",
        "name": "DePuy Hip Lawsuit Calculator"
    },
    {
        "id": "depuy-knee",
        "name": "DePuy Knee Lawsuit Calculator"
    },
    {
        "id": "dialysis",
        "name": "Dialysis Lawsuit Calculator"
    },
    {
        "id": "dirt-bike-insurance",
        "name": "Dirt Bike Insurance Calculator"
    },
    {
        "id": "disability",
        "name": "Disability Benefits Calculator"
    },
    {
        "id": "divorce",
        "name": "Divorce Settlement Calculator"
    },
    {
        "id": "do-insurance",
        "name": "D&O Insurance Calculator"
    },
    {
        "id": "dog-bite",
        "name": "Dog Bite Settlement Calculator"
    },
    {
        "id": "down-payment",
        "name": "Down Payment Calculator"
    },
    {
        "id": "drunk-driving",
        "name": "DUI Calculator"
    },
    {
        "id": "dti",
        "name": "DTI Calculator"
    },
    {
        "id": "due-date",
        "name": "Due Date Auditor 2026"
    },
    {
        "id": "DUI",
        "name": "DUI Cost Calculator"
    },
    {
        "id": "e-bike",
        "name": "E-Bike Accident Calculator"
    },
    {
        "id": "e-scooter",
        "name": "E-Scooter Accident Calculator"
    },
    {
        "id": "earthquake-insurance",
        "name": "Earthquake Insurance Calculator"
    },
    {
        "id": "ebt",
        "name": "EBT Calculator"
    },
    {
        "id": "electrician-insurance",
        "name": "Electrician Insurance Calculator"
    },
    {
        "id": "electrocution",
        "name": "Electrocution Injury Calculator"
    },
    {
        "id": "elevator-accident",
        "name": "Elevator Accident Calculator"
    },
    {
        "id": "elmiron",
        "name": "Elmiron Vision Loss Calculator"
    },
    {
        "id": "environmental",
        "name": "Environmental Lawsuit Calculator"
    },
    {
        "id": "eo-insurance",
        "name": "E&O Insurance Calculator"
    },
    {
        "id": "epli",
        "name": "Wrongful Termination Settlement Calculator"
    },
    {
        "id": "era",
        "name": "Emergency Rental Assistance Calculator"
    },
    {
        "id": "escalator-injury",
        "name": "Escalator Injury Calculator"
    },
    {
        "id": "espp",
        "name": "ESPP Calculator"
    },
    {
        "id": "essure",
        "name": "Essure Lawsuit Calculator"
    },
    {
        "id": "estate-tax",
        "name": "Estate Tax Calculator"
    },
    {
        "id": "estimated-tax",
        "name": "Estimated Tax Calculator"
    },
    {
        "id": "ethicon-mesh",
        "name": "Ethicon Hernia Mesh Calculator"
    },
    {
        "id": "event-insurance",
        "name": "Event Insurance Calculator"
    },
    {
        "id": "exotic-car-insurance",
        "name": "Exotic Car Insurance Calculator"
    },
    {
        "id": "explosion",
        "name": "Explosion Injury Calculator"
    },
    {
        "id": "factory-injury",
        "name": "Factory Injury Calculator"
    },
    {
        "id": "fafsa",
        "name": "FAFSA Calculator"
    },
    {
        "id": "fela",
        "name": "FELA Railroad Injury Settlement Calculator"
    },
    {
        "id": "fentanyl-exposure",
        "name": "Fentanyl Exposure Calculator"
    },
    {
        "id": "firefighter-foam",
        "name": "Firefighter Foam Lawsuit Calculator"
    },
    {
        "id": "fleet-insurance",
        "name": "Fleet Insurance Calculator"
    },
    {
        "id": "flood-insurance",
        "name": "Flood Insurance Calculator"
    },
    {
        "id": "fluoroquinolone",
        "name": "Fluoroquinolone Lawsuit Calculator"
    },
    {
        "id": "food-poisoning",
        "name": "Food Poisoning Calculator"
    },
    {
        "id": "food-stamps",
        "name": "Food Stamps Calculator"
    },
    {
        "id": "food-truck-insurance",
        "name": "Food Truck Insurance Calculator"
    },
    {
        "id": "forklift",
        "name": "Forklift Accident Calculator"
    },
    {
        "id": "freelance-tax",
        "name": "Freelance Tax Calculator"
    },
    {
        "id": "fsa",
        "name": "FSA Calculator"
    },
    {
        "id": "gadolinium",
        "name": "Gadolinium Lawsuit Calculator"
    },
    {
        "id": "garage-accident",
        "name": "Garage Accident Calculator"
    },
    {
        "id": "gas-explosion",
        "name": "Gas Explosion Calculator"
    },
    {
        "id": "general-liability",
        "name": "General Liability Insurance Calculator"
    },
    {
        "id": "gi-bill",
        "name": "GI Bill Calculator"
    },
    {
        "id": "gift-tax",
        "name": "Gift Tax Calculator"
    },
    {
        "id": "glp1-vision",
        "name": "GLP-1 Vision Loss Settlement Calculator"
    },
    {
        "id": "golf-cart-insurance",
        "name": "Golf Cart Insurance Calculator"
    },
    {
        "id": "golf-cart",
        "name": "Golf Cart Accident Calculator"
    },
    {
        "id": "gpa",
        "name": "GPA Calculator"
    },
    {
        "id": "grade",
        "name": "Grade Calculator"
    },
    {
        "id": "grocery-store-injury",
        "name": "Grocery Store Injury Calculator"
    },
    {
        "id": "gym-injury",
        "name": "Gym Injury Calculator"
    },
    {
        "id": "gym-insurance",
        "name": "Gym Insurance Calculator"
    },
    {
        "id": "hair-relaxer",
        "name": "Hair Relaxer Lawsuit Calculator"
    },
    {
        "id": "health-insurance",
        "name": "Health Insurance Calculator"
    },
    {
        "id": "heloc",
        "name": "HELOC Calculator"
    },
    {
        "id": "hernia-mesh",
        "name": "Bard Hernia Mesh Settlement Calculator"
    },
    {
        "id": "hip-implant",
        "name": "Hip Implant Lawsuit Calculator"
    },
    {
        "id": "hit-and-run",
        "name": "Hit and Run Calculator"
    },
    {
        "id": "home-afford",
        "name": "Home Affordability Calculator"
    },
    {
        "id": "hotel-injury",
        "name": "Hotel Injury Calculator"
    },
    {
        "id": "hsa",
        "name": "HSA Calculator"
    },
    {
        "id": "hud-housing",
        "name": "HUD Housing Calculator"
    },
    {
        "id": "hurricane-insurance",
        "name": "Hurricane Insurance Calculator"
    },
    {
        "id": "hvac-insurance",
        "name": "HVAC Insurance Calculator"
    },
    {
        "id": "inheritance",
        "name": "Inheritance Calculator"
    },
    {
        "id": "invokana",
        "name": "Invokana Lawsuit Calculator"
    },
    {
        "id": "ivc-filter",
        "name": "IVC Filter Lawsuit Calculator"
    },
    {
        "id": "jet-ski",
        "name": "Jet Ski Accident Calculator"
    },
    {
        "id": "jewelry-insurance",
        "name": "Jewelry Insurance Calculator"
    },
    {
        "id": "knee-implant",
        "name": "Knee Replacement Lawsuit Calculator"
    },
    {
        "id": "landscaping-insurance",
        "name": "Landscaping Insurance Calculator"
    },
    {
        "id": "lead-poisoning",
        "name": "Lead Poisoning Settlement Calculator"
    },
    {
        "id": "lemon-law",
        "name": "Lemon Law Calculator"
    },
    {
        "id": "life-insurance",
        "name": "Life Insurance Calculator"
    },
    {
        "id": "liheap",
        "name": "LIHEAP Calculator"
    },
    {
        "id": "llc-tax",
        "name": "LLC Tax Calculator"
    },
    {
        "id": "loan-payoff",
        "name": "Loan Payoff Calculator"
    },
    {
        "id": "loan",
        "name": "Loan Calculator"
    },
    {
        "id": "ltd",
        "name": "Long Term Disability Calculator"
    },
    {
        "id": "lung-disease",
        "name": "Lung Disease Settlement Calculator"
    },
    {
        "id": "lupron",
        "name": "Lupron Side Effects Calculator"
    },
    {
        "id": "malpractice",
        "name": "Medical Malpractice Calculator"
    },
    {
        "id": "manufactured-home-insurance",
        "name": "Manufactured Home Insurance Calculator"
    },
    {
        "id": "medicaid",
        "name": "Medicaid Eligibility Calculator"
    },
    {
        "id": "medicare-part-b",
        "name": "Medicare Part B Calculator"
    },
    {
        "id": "medicare-part-d",
        "name": "Medicare Part D Calculator"
    },
    {
        "id": "medicare-premium",
        "name": "Medicare Premium Calculator"
    },
    {
        "id": "mesothelioma",
        "name": "Mesothelioma Settlement Calculator"
    },
    {
        "id": "metal-hip",
        "name": "Metal-on-Metal Hip Lawsuit Calculator"
    },
    {
        "id": "mining-injury",
        "name": "Mining Injury Calculator"
    },
    {
        "id": "mirena",
        "name": "Mirena IUD Lawsuit Calculator"
    },
    {
        "id": "mobile-home-insurance",
        "name": "Mobile Home Insurance Calculator"
    },
    {
        "id": "mortgage",
        "name": "Mortgage Calculator"
    },
    {
        "id": "motorcycle-accident",
        "name": "Motorcycle Accident Calculator"
    },
    {
        "id": "nec-formula",
        "name": "NEC Formula Lawsuit Calculator"
    },
    {
        "id": "nexium",
        "name": "Nexium Kidney Lawsuit Calculator"
    },
    {
        "id": "nexplanon",
        "name": "Nexplanon Lawsuit Calculator"
    },
    {
        "id": "nonprofit-insurance",
        "name": "Non-Profit Insurance Calculator"
    },
    {
        "id": "nursing-home",
        "name": "Nursing Home Abuse Calculator"
    },
    {
        "id": "offshore",
        "name": "Jones Act Settlement Calculator"
    },
    {
        "id": "oil-rig",
        "name": "Oil Rig Injury Calculator"
    },
    {
        "id": "opioid-addiction",
        "name": "Opioid Addiction Calculator"
    },
    {
        "id": "overtime",
        "name": "Overtime Pay Calculator"
    },
    {
        "id": "ovulation",
        "name": "Ovulation Calculator"
    },
    {
        "id": "oxycontin",
        "name": "OxyContin Lawsuit Calculator"
    },
    {
        "id": "ozempic",
        "name": "Ozempic Settlement Calculator"
    },
    {
        "id": "paragard",
        "name": "Paragard IUD Lawsuit Calculator"
    },
    {
        "id": "paraquat",
        "name": "Paraquat Lawsuit Calculator"
    },
    {
        "id": "parking-lot-accident",
        "name": "Parking Lot Accident Calculator"
    },
    {
        "id": "pedestrian-accident",
        "name": "Pedestrian Accident Calculator"
    },
    {
        "id": "pelvic-mesh",
        "name": "Pelvic Mesh Lawsuit Calculator"
    },
    {
        "id": "pension",
        "name": "Pension Calculator"
    },
    {
        "id": "percentage",
        "name": "Percentage Calculator"
    },
    {
        "id": "pet-insurance",
        "name": "Pet Insurance Calculator"
    },
    {
        "id": "pfas",
        "name": "PFAS Lawsuit Calculator"
    },
    {
        "id": "philips-ventilator",
        "name": "Philips CPAP Settlement Calculator"
    },
    {
        "id": "pipeline",
        "name": "Pipeline Injury Calculator"
    },
    {
        "id": "playground-injury",
        "name": "Playground Injury Calculator"
    },
    {
        "id": "plumber-insurance",
        "name": "Plumber Insurance Calculator"
    },
    {
        "id": "pmi",
        "name": "PMI Calculator"
    },
    {
        "id": "pool-drowning",
        "name": "Pool Drowning Calculator"
    },
    {
        "id": "ppi",
        "name": "PPI Lawsuit Calculator"
    },
    {
        "id": "pradaxa",
        "name": "Pradaxa Lawsuit Calculator"
    },
    {
        "id": "pregnancy",
        "name": "Pregnancy Calculator"
    },
    {
        "id": "prilosec",
        "name": "Prilosec Kidney Lawsuit Calculator"
    },
    {
        "id": "product-liability",
        "name": "Product Liability Calculator"
    },
    {
        "id": "professional-liability",
        "name": "Professional Liability Calculator"
    },
    {
        "id": "property-division",
        "name": "Property Division Calculator"
    },
    {
        "id": "quarterly-tax",
        "name": "Quarterly Tax Calculator"
    },
    {
        "id": "refinance",
        "name": "Refinance Calculator"
    },
    {
        "id": "refinery",
        "name": "Refinery Accident Calculator"
    },
    {
        "id": "rental-income",
        "name": "Rental Income Calculator"
    },
    {
        "id": "renters-insurance",
        "name": "Renters Insurance Calculator"
    },
    {
        "id": "resort-injury",
        "name": "Resort Injury Calculator"
    },
    {
        "id": "restaurant-injury",
        "name": "Restaurant Injury Calculator"
    },
    {
        "id": "restaurant-insurance",
        "name": "Restaurant Insurance Calculator"
    },
    {
        "id": "retail-store-injury",
        "name": "Retail Store Injury Calculator"
    },
    {
        "id": "retirement",
        "name": "Retirement Calculator"
    },
    {
        "id": "rideshare-accident",
        "name": "Rideshare Accident Calculator"
    },
    {
        "id": "rideshare-insurance",
        "name": "Rideshare Insurance Calculator"
    },
    {
        "id": "risperdal",
        "name": "Risperdal Lawsuit Calculator"
    },
    {
        "id": "rmd",
        "name": "RMD Calculator"
    },
    {
        "id": "roofing-insurance",
        "name": "Roofing Insurance Calculator"
    },
    {
        "id": "roth-ira",
        "name": "Roth IRA Calculator"
    },
    {
        "id": "roundup",
        "name": "Roundup Settlement Calculator"
    },
    {
        "id": "rsu",
        "name": "RSU Calculator"
    },
    {
        "id": "rv-insurance",
        "name": "RV Insurance Calculator"
    },
    {
        "id": "s-corp-tax",
        "name": "S Corp Tax Calculator"
    },
    {
        "id": "salary",
        "name": "Salary Calculator"
    },
    {
        "id": "salon-insurance",
        "name": "Salon Insurance Calculator"
    },
    {
        "id": "scaffolding",
        "name": "Scaffolding Accident Calculator"
    },
    {
        "id": "school-injury",
        "name": "School Injury Calculator"
    },
    {
        "id": "scientific",
        "name": "Scientific Calculator"
    },
    {
        "id": "section-8",
        "name": "Section 8 Calculator"
    },
    {
        "id": "self-employment",
        "name": "Self Employment Tax Calculator"
    },
    {
        "id": "severance",
        "name": "Severance Pay Calculator"
    },
    {
        "id": "shoulder-implant",
        "name": "Shoulder Implant Lawsuit Calculator"
    },
    {
        "id": "side-hustle-tax",
        "name": "Side Hustle Tax Calculator"
    },
    {
        "id": "silicosis",
        "name": "Silicosis Settlement Calculator"
    },
    {
        "id": "ski-accident",
        "name": "Ski Accident Calculator"
    },
    {
        "id": "slip-and-fall",
        "name": "Slip and Fall Settlement Calculator"
    },
    {
        "id": "smith-nephew-knee",
        "name": "Smith & Nephew Knee Calculator"
    },
    {
        "id": "snap",
        "name": "SNAP Benefits Calculator"
    },
    {
        "id": "snowboard-injury",
        "name": "Snowboard Injury Calculator"
    },
    {
        "id": "snowmobile-insurance",
        "name": "Snowmobile Insurance Calculator"
    },
    {
        "id": "social-media",
        "name": "Social Media Addiction Lawsuit Calculator"
    },
    {
        "id": "social-security",
        "name": "Social Security Calculator"
    },
    {
        "id": "spinal-cord",
        "name": "Spinal Cord Injury Calculator"
    },
    {
        "id": "spinal-fusion",
        "name": "Spinal Fusion Hardware Calculator"
    },
    {
        "id": "spine-implant",
        "name": "Spine Implant Lawsuit Calculator"
    },
    {
        "id": "sports-injury",
        "name": "Sports Injury Calculator"
    },
    {
        "id": "square-footage",
        "name": "Square Footage Calculator"
    },
    {
        "id": "sr22",
        "name": "SR-22 Insurance Cost Calculator"
    },
    {
        "id": "ssdi",
        "name": "SSDI Back Pay Calculator"
    },
    {
        "id": "ssi",
        "name": "SSI Calculator"
    },
    {
        "id": "stadium-injury",
        "name": "Stadium Injury Calculator"
    },
    {
        "id": "stock-option",
        "name": "Stock Option Calculator"
    },
    {
        "id": "structured-settlement",
        "name": "Structured Settlement Calculator"
    },
    {
        "id": "stryker-hip",
        "name": "Stryker Hip Lawsuit Calculator"
    },
    {
        "id": "stryker-knee",
        "name": "Stryker Knee Lawsuit Calculator"
    },
    {
        "id": "student-insurance",
        "name": "Student Insurance Calculator"
    },
    {
        "id": "student-loan",
        "name": "Student Loan Calculator"
    },
    {
        "id": "suboxone",
        "name": "Suboxone Tooth Decay Calculator"
    },
    {
        "id": "subway-accident",
        "name": "Subway Accident Calculator"
    },
    {
        "id": "talcum-powder",
        "name": "Talcum Powder Settlement Calculator"
    },
    {
        "id": "tanf",
        "name": "TANF Benefits Calculator"
    },
    {
        "id": "tax",
        "name": "Tax Calculator"
    },
    {
        "id": "tbi",
        "name": "TBI Settlement Calculator"
    },
    {
        "id": "tepezza",
        "name": "Tepezza Hearing Loss Lawsuit Calculator"
    },
    {
        "id": "testosterone",
        "name": "Testosterone Lawsuit Calculator"
    },
    {
        "id": "textured-implant",
        "name": "Textured Breast Implant Calculator"
    },
    {
        "id": "theme-park",
        "name": "Theme Park Injury Calculator"
    },
    {
        "id": "time-calculator",
        "name": "Time Calculator"
    },
    {
        "id": "tip",
        "name": "2026 Tip Calculator | Gratuity Gold Precision Engine"
    },
    {
        "id": "townhouse-insurance",
        "name": "Townhouse Insurance Calculator"
    },
    {
        "id": "toxic-tort",
        "name": "Toxic Tort Settlement Calculator"
    },
    {
        "id": "trailer-insurance",
        "name": "Trailer Insurance Calculator"
    },
    {
        "id": "train-accident",
        "name": "Train Accident Calculator"
    },
    {
        "id": "transvaginal-mesh",
        "name": "Transvaginal Mesh Lawsuit Calculator"
    },
    {
        "id": "travel-insurance",
        "name": "Travel Insurance Calculator"
    },
    {
        "id": "trip-cancellation",
        "name": "Trip Cancellation Calculator"
    },
    {
        "id": "truck-accident",
        "name": "Truck Accident Settlement Calculator"
    },
    {
        "id": "trucking-insurance",
        "name": "Trucking Insurance Calculator"
    },
    {
        "id": "trust-tax",
        "name": "Trust Tax Calculator"
    },
    {
        "id": "tylenol",
        "name": "Tylenol Autism Lawsuit Calculator"
    },
    {
        "id": "uloric",
        "name": "Uloric Lawsuit Calculator"
    },
    {
        "id": "umbrella-insurance",
        "name": "Umbrella Insurance Calculator"
    },
    {
        "id": "unemployment",
        "name": "Unemployment Benefits Calculator"
    },
    {
        "id": "va-disability",
        "name": "VA Disability Calculator"
    },
    {
        "id": "valet-accident",
        "name": "Valet Accident Calculator"
    },
    {
        "id": "viagra-melanoma",
        "name": "Viagra Melanoma Lawsuit Calculator"
    },
    {
        "id": "vision-insurance",
        "name": "Vision Insurance Calculator"
    },
    {
        "id": "wage-garnishment",
        "name": "Wage Garnishment Calculator"
    },
    {
        "id": "watch-insurance",
        "name": "Watch Insurance Calculator"
    },
    {
        "id": "water-contamination",
        "name": "Water Contamination Lawsuit Calculator"
    },
    {
        "id": "waterpark-injury",
        "name": "Waterpark Injury Calculator"
    },
    {
        "id": "wedding-insurance",
        "name": "Wedding Insurance Calculator"
    },
    {
        "id": "welding",
        "name": "Welding Injury Calculator"
    },
    {
        "id": "whiplash",
        "name": "Whiplash Settlement Calculator"
    },
    {
        "id": "wic",
        "name": "WIC Benefits Calculator"
    },
    {
        "id": "windstorm-insurance",
        "name": "Windstorm Insurance Calculator"
    },
    {
        "id": "workers-comp-premium",
        "name": "Workers Comp Premium Calculator"
    },
    {
        "id": "workers-comp",
        "name": "Workers Comp Calculator"
    },
    {
        "id": "wright-hip",
        "name": "Wright Hip Lawsuit Calculator"
    },
    {
        "id": "wrongful-death",
        "name": "Wrongful Death Calculator"
    },
    {
        "id": "xarelto",
        "name": "Xarelto Lawsuit Calculator"
    },
    {
        "id": "zantac",
        "name": "Zantac Cancer Lawsuit Calculator"
    },
    {
        "id": "zimmer-hip",
        "name": "Zimmer Hip Lawsuit Calculator"
    }
];
