/**
 * Category Mapping for Related Calculators
 * Maps each calculator to its category for internal linking
 */

export type Category = 'legal' | 'finance' | 'insurance' | 'family' | 'medical' | 'health';

export const CATEGORY_MAP: Record<string, Category> = {
    // Legal & Injury
    'car-accident': 'legal',
    'truck-accident': 'legal',
    'motorcycle-accident': 'legal',
    'slip-and-fall': 'legal',
    'workers-comp': 'legal',
    'wrongful-death': 'legal',
    'malpractice': 'legal',
    'dog-bite': 'legal',
    'nursing-home': 'legal',
    'birth-injury': 'legal',
    'spinal-cord': 'legal',
    'tbi': 'legal',
    'burn-injury': 'legal',
    'whiplash': 'legal',
    'mesothelioma': 'legal',
    'asbestos': 'legal',
    'product-liability': 'legal',
    'crane': 'legal',
    'scaffolding': 'legal',
    'welding': 'legal',
    'pipeline': 'legal',
    'refinery': 'legal',
    'mining-injury': 'legal',
    'factory-injury': 'legal',
    'forklift': 'legal',
    'explosion': 'legal',
    'gas-explosion': 'legal',
    'chemical-burn': 'legal',
    'benzene': 'legal',
    'electrocution': 'legal',
    'toxic-tort': 'legal',
    'environmental': 'legal',
    'lead-poisoning': 'medical',
    'water-contamination': 'legal',
    'pfas': 'legal',
    '3m-earplug': 'medical',
    'roundup': 'medical',
    'zantac': 'medical',
    'baby-formula': 'medical',
    'tylenol': 'medical',
    'suboxone': 'medical',
    'elmiron': 'medical',
    'bard-powerport': 'medical',
    'construction-accident': 'legal',
    'pedestrian-accident': 'legal',
    'hit-and-run': 'legal',
    'drunk-driving': 'legal',
    'DUI': 'legal',
    'rideshare-accident': 'legal',
    'commercial-vehicle': 'legal',
    '18-wheeler': 'legal',
    'aviation': 'legal',
    'fela': 'legal',
    'oil-rig': 'legal',
    'offshore': 'legal',
    'pool-drowning': 'legal',
    'lemon-law': 'legal',
    'bail-bond': 'legal',
    'structured-settlement': 'legal',

    // Medical/Drug Lawsuits
    'hernia-mesh': 'medical',
    'hip-implant': 'medical',
    'knee-implant': 'medical',
    'talcum-powder': 'medical',
    'camp-lejeune': 'medical',
    'paragard': 'medical',
    'paraquat': 'medical',
    'ozempic': 'medical',
    'glp1-vision': 'medical',
    'tepezza': 'medical',
    'depo-provera': 'medical',
    'hair-relaxer': 'medical',
    'cpap': 'medical',
    'social-media': 'medical',
    'lung-disease': 'medical',
    'silicosis': 'medical',
    'black-lung': 'medical',

    // Finance & Tax
    'mortgage': 'finance',
    'loan-payoff': 'finance',
    'refinance': 'finance',
    'heloc': 'finance',
    'home-afford': 'finance',
    'down-payment': 'finance',
    'closing-cost': 'finance',
    'pmi': 'finance',
    'dti': 'finance',
    'tax': 'finance',
    'capital-gains': 'finance',
    'estate-tax': 'finance',
    'crypto-tax': 'finance',
    'self-employment': 'finance',
    'retirement': 'finance',
    '401k': 'finance',
    'roth-ira': 'finance',
    'rmd': 'finance',
    'pension': 'finance',
    'annuity': 'finance',
    'student-loan': 'finance',
    'fafsa': 'finance',
    '529': 'finance',
    'social-security': 'finance',
    'ssdi': 'finance',
    'unemployment': 'finance',
    'severance': 'finance',
    'overtime': 'finance',
    'wage-garnishment': 'finance',
    'gi-bill': 'finance',
    'va-disability': 'finance',
    'disability': 'finance',
    'ltd': 'finance',
    'tip': 'finance',

    // Insurance
    'auto-insurance': 'insurance',
    'health-insurance': 'insurance',
    'life-insurance': 'insurance',
    'renters-insurance': 'insurance',
    'pet-insurance': 'insurance',
    'boat-insurance': 'insurance',
    'umbrella-insurance': 'insurance',
    'sr22': 'insurance',

    // Family
    'child-support': 'family',
    'alimony': 'family',
    'divorce': 'family',
    'property-division': 'family',

    // Health
    'bmi': 'health',
    'calorie': 'health',
};

export const CATEGORY_NAMES: Record<Category, string> = {
    legal: 'Legal & Injury',
    finance: 'Finance & Tax',
    insurance: 'Insurance',
    family: 'Family & Support',
    medical: 'Medical Lawsuits',
    health: 'Health & Fitness',
};

export const CALCULATOR_NAMES: Record<string, string> = {
    'car-accident': 'Car Accident',
    'truck-accident': 'Truck Accident',
    'motorcycle-accident': 'Motorcycle',
    'slip-and-fall': 'Slip and Fall',
    'workers-comp': 'Workers\' Comp',
    'wrongful-death': 'Wrongful Death',
    'malpractice': 'Malpractice',
    'dog-bite': 'Dog Bite',
    'nursing-home': 'Nursing Home',
    'birth-injury': 'Birth Injury',
    'spinal-cord': 'Spinal Cord',
    'tbi': 'TBI',
    'burn-injury': 'Burn Injury',
    'whiplash': 'Whiplash',
    'mesothelioma': 'Mesothelioma',
    'asbestos': 'Asbestos',
    'product-liability': 'Product Liability',
    'crane': 'Crane Injury',
    'scaffolding': 'Scaffolding',
    'welding': 'Welding Injury',
    'pipeline': 'Pipeline',
    'refinery': 'Refinery',
    'mining-injury': 'Mining Injury',
    'factory-injury': 'Factory Injury',
    'forklift': 'Forklift',
    'explosion': 'Explosion',
    'gas-explosion': 'Gas Explosion',
    'chemical-burn': 'Chemical Burn',
    'benzene': 'Benzene',
    'electrocution': 'Electrocution',
    'construction-accident': 'Construction',
    'pedestrian-accident': 'Pedestrian',
    'hit-and-run': 'Hit and Run',
    'drunk-driving': 'Drunk Driving',
    'DUI': 'DUI',
    'rideshare-accident': 'Rideshare',
    'commercial-vehicle': 'Commercial Vehicle',
    '18-wheeler': '18-Wheeler',
    'aviation': 'Aviation',
    'fela': 'FELA Railroad',
    'oil-rig': 'Oil Rig',
    'offshore': 'Offshore',
    'pool-drowning': 'Pool Drowning',
    'lemon-law': 'Lemon Law',
    'bail-bond': 'Bail Bond',
    'structured-settlement': 'Structured Settlement',
    'hernia-mesh': 'Hernia Mesh',
    'hip-implant': 'Hip Implant',
    'knee-implant': 'Knee Implant',
    'talcum-powder': 'Talcum Powder',
    'camp-lejeune': 'Camp Lejeune',
    'paragard': 'Paragard IUD',
    'paraquat': 'Paraquat',
    'ozempic': 'Ozempic',
    'glp1-vision': 'GLP-1 Vision',
    'tepezza': 'Tepezza',
    'depo-provera': 'Depo-Provera',
    'hair-relaxer': 'Hair Relaxer',
    'cpap': 'CPAP',
    'social-media': 'Social Media',
    'mortgage': 'Mortgage',
    'loan-payoff': 'Loan Payoff',
    'refinance': 'Refinance',
    'heloc': 'HELOC',
    'home-afford': 'Home Affordability',
    'down-payment': 'Down Payment',
    'closing-cost': 'Closing Cost',
    'pmi': 'PMI',
    'dti': 'DTI',
    'tax': 'Income Tax',
    'capital-gains': 'Capital Gains',
    'estate-tax': 'Estate Tax',
    'crypto-tax': 'Crypto Tax',
    'self-employment': 'Self Employment',
    'retirement': 'Retirement',
    '401k': '401k',
    'roth-ira': 'Roth IRA',
    'rmd': 'RMD',
    'pension': 'Pension',
    'annuity': 'Annuity',
    'student-loan': 'Student Loan',
    'fafsa': 'FAFSA',
    '529': '529 Plan',
    'social-security': 'Social Security',
    'ssdi': 'SSDI',
    'unemployment': 'Unemployment',
    'severance': 'Severance',
    'overtime': 'Overtime',
    'wage-garnishment': 'Wage Garnishment',
    'gi-bill': 'GI Bill',
    'va-disability': 'VA Disability',
    'disability': 'Disability',
    'ltd': 'LTD',
    'tip': 'Tip Calculator',
    'auto-insurance': 'Auto Insurance',
    'health-insurance': 'Health Insurance',
    'life-insurance': 'Life Insurance',
    'renters-insurance': 'Renters Insurance',
    'pet-insurance': 'Pet Insurance',
    'boat-insurance': 'Boat Insurance',
    'umbrella-insurance': 'Umbrella Insurance',
    'sr22': 'SR-22',
    'child-support': 'Child Support',
    'alimony': 'Alimony',
    'divorce': 'Divorce',
    'property-division': 'Property Division',
    'bmi': 'BMI',
    'calorie': 'Calorie',
    'lung-disease': 'Lung Disease',
    'silicosis': 'Silicosis',
    'black-lung': 'Black Lung',
    'toxic-tort': 'Toxic Tort',
    'environmental': 'Environmental',
    'lead-poisoning': 'Lead Poisoning',
    'water-contamination': 'Water Contamination',
    'pfas': 'PFAS Lawsuit',
    '3m-earplug': '3M Earplug',
    'roundup': 'Roundup Lymphoma',
    'zantac': 'Zantac Cancer',
    'baby-formula': 'Baby Formula NEC',
    'tylenol': 'Tylenol Autism',
    'suboxone': 'Suboxone Tooth Decay',
    'elmiron': 'Elmiron Vision Loss',
    'bard-powerport': 'Bard PowerPort',
};

/**
 * Get related calculators for a given calculator
 * Returns up to 5 calculators from the same category (excluding current)
 */
export function getRelatedCalculators(currentCalc: string, count: number = 5): { id: string; name: string }[] {
    const category = CATEGORY_MAP[currentCalc];
    if (!category) return [];

    const related = Object.entries(CATEGORY_MAP)
        .filter(([id, cat]) => cat === category && id !== currentCalc)
        .map(([id]) => ({ id, name: CALCULATOR_NAMES[id] || id }))
        .slice(0, count);

    return related;
}

/**
 * Get category info for a calculator
 */
export function getCategoryInfo(calcId: string): { category: Category; name: string } | null {
    const category = CATEGORY_MAP[calcId];
    if (!category) return null;
    return { category, name: CATEGORY_NAMES[category] };
}
