/**
 * V5.0 Layout Ownership Registry
 * Centralized source of truth to determine which shell owns a specific route.
 * This prevents multiple layouts from rendering global elements (headers/footers) simultaneously.
 */

export type LayoutShellType = 'LEGACY' | 'S_CLASS' | 'MINIMAL';

export const LAYOUT_CONFIG: Record<string, LayoutShellType> = {
    "/truck-accident": 'S_CLASS',
    "/1099-tax": 'S_CLASS',
    "/18-wheeler": 'S_CLASS',
    "/3m-earplug": 'S_CLASS',
    "/529": 'S_CLASS',
    "/DUI": 'S_CLASS',
    "/abilify": 'S_CLASS',
    "/accutane": 'S_CLASS',
    "/afff": 'S_CLASS',
    "/airbnb-income": 'S_CLASS',
    "/ozempic": 'S_CLASS',
    "/roundup": 'S_CLASS',
    "/401k-growth": 'S_CLASS',
    "/car-accident": 'S_CLASS',
    "/bmi": 'S_CLASS',
    "/mortgage": 'S_CLASS',
    "/unemployment": 'S_CLASS',
    "/va-disability": 'S_CLASS',
    "/tip": 'S_CLASS',
    "/ssdi": 'S_CLASS',
    "/social-security": 'S_CLASS',
    "/roth-ira": 'S_CLASS',
    "/pmi": 'S_CLASS',
    "/pet-insurance": 'S_CLASS',
    "/loan-payoff": 'S_CLASS',
    "/fafsa": 'S_CLASS',
    "/down-payment": 'S_CLASS',
    "/dti": 'S_CLASS',
    "/calorie": 'S_CLASS',
    "/alimony": 'S_CLASS',
    "/amusement-park": 'S_CLASS',
    "/ankle-implant": 'S_CLASS',
    "/annuity": 'S_CLASS',
    "/antique-car-insurance": 'S_CLASS',
    "/art-insurance": 'S_CLASS',
    "/asbestos": 'S_CLASS',
    "/atrium-mesh": 'S_CLASS',
    "/atv-accident": 'S_CLASS',
    "/atv-insurance": 'S_CLASS',
    "/auto-insurance": 'S_CLASS',
    "/aviation": 'S_CLASS',
    "/baby-formula": 'S_CLASS',
    "/bail-bond": 'S_CLASS',
    "/bair-hugger": 'S_CLASS',
    "/bar-insurance": 'S_CLASS',
    "/bard-mesh": 'S_CLASS',
    "/bard-powerport": 'S_CLASS',
    "/benzene": 'S_CLASS',
    "/binary": 'S_CLASS',
    "/conversion": 'S_CLASS',
    "/date": 'S_CLASS',
    "/biomet-hip": 'S_CLASS',
    "/birth-injury": 'S_CLASS',
    "/black-lung": 'S_CLASS',
    "/boat-insurance": 'S_CLASS',
    "/boating-accident": 'S_CLASS',
    "/bone-graft": 'S_CLASS',
    "/bonus-tax": 'S_CLASS',
    "/breast-implant": 'S_CLASS',
    "/burn-injury": 'S_CLASS',
    "/bus-accident": 'S_CLASS',
    "/business-insurance": 'S_CLASS',
    "/camp-lejeune": 'S_CLASS',
    "/camper-insurance": 'S_CLASS',
    "/capital-gains": 'S_CLASS',
    "/casino-injury": 'S_CLASS',
    "/charitable-donation": 'S_CLASS',
    "/chemical-burn": 'S_CLASS',
    "/child-care-subsidy": 'S_CLASS',
    "/child-support": 'S_CLASS',
    "/classic-car-insurance": 'S_CLASS',
    "/closing-cost": 'S_CLASS',
    "/collectible-insurance": 'S_CLASS',
    "/commercial-auto": 'S_CLASS',
    "/commercial-insurance": 'S_CLASS',
    "/commercial-vehicle": 'S_CLASS',
    "/commission": 'S_CLASS',
    "/concert-injury": 'S_CLASS',
    "/condo-insurance": 'S_CLASS',
    "/construction-accident": 'S_CLASS',
    "/contractor-insurance": 'S_CLASS',
    "/cpap": 'S_CLASS',
    "/crane": 'S_CLASS',
    "/crossfit-injury": 'S_CLASS',
    "/crowd-crush": 'S_CLASS',
    "/cruise-insurance": 'S_CLASS',
    "/crypto-tax": 'S_CLASS',
    "/cyber-insurance": 'S_CLASS',
    "/daycare-injury": 'S_CLASS',
    "/daycare-insurance": 'S_CLASS',
    "/delivery-insurance": 'S_CLASS',
    "/dental-insurance": 'S_CLASS',
    "/depo-provera": 'S_CLASS',
    "/depuy-hip": 'S_CLASS',
    "/depuy-knee": 'S_CLASS',
    "/dialysis": 'S_CLASS',
    "/dirt-bike-insurance": 'S_CLASS',
    "/disability": 'S_CLASS',
    "/divorce": 'S_CLASS',
    "/do-insurance": 'S_CLASS',
    "/dog-bite": 'S_CLASS',
    "/drunk-driving": 'S_CLASS',
    "/e-bike": 'S_CLASS',
    "/e-scooter": 'S_CLASS',
    "/earthquake-insurance": 'S_CLASS',
    "/ebt": 'S_CLASS',
    "/electrician-insurance": 'S_CLASS',
    "/electrocution": 'S_CLASS',
    "/elevator-accident": 'S_CLASS',
    "/elmiron": 'S_CLASS',
    "/environmental": 'S_CLASS',
    "/eo-insurance": 'S_CLASS',
    "/epli": 'S_CLASS',
    "/era": 'S_CLASS',
    "/escalator-injury": 'S_CLASS',
    "/espp": 'S_CLASS',
    "/essure": 'S_CLASS',
    "/estate-tax": 'S_CLASS',
    "/estimated-tax": 'S_CLASS',
    "/ethicon-mesh": 'S_CLASS',
    "/event-insurance": 'S_CLASS',
    "/exotic-car-insurance": 'S_CLASS',
    "/explosion": 'S_CLASS',
    "/factory-injury": 'S_CLASS',
    "/fela": 'S_CLASS',
    "/fentanyl-exposure": 'S_CLASS',
    "/firefighter-foam": 'S_CLASS',
    "/fleet-insurance": 'S_CLASS',
    "/flood-insurance": 'S_CLASS',
    "/fluoroquinolone": 'S_CLASS',
    "/food-poisoning": 'S_CLASS',
    "/food-stamps": 'S_CLASS',
    "/food-truck-insurance": 'S_CLASS',
    "/forklift": 'S_CLASS',
    "/freelance-tax": 'S_CLASS',
    "/gadolinium": 'S_CLASS',
    "/garage-accident": 'S_CLASS',
    "/gas-explosion": 'S_CLASS',
    "/general-liability": 'S_CLASS',
    "/gi-bill": 'S_CLASS',
    "/gift-tax": 'S_CLASS',
    "/glp1-vision": 'S_CLASS',
    "/golf-cart": 'S_CLASS',
    "/golf-cart-insurance": 'S_CLASS',
    "/grocery-store-injury": 'S_CLASS',
    "/gym-injury": 'S_CLASS',
    "/gym-insurance": 'S_CLASS',
    "/v3-sandbox/truck-flagship": 'S_CLASS',
    "/hair-relaxer": 'S_CLASS',
    "/health-insurance": 'S_CLASS',
    "/heloc": 'S_CLASS',
    "/hernia-mesh": 'S_CLASS',
    "/hip-implant": 'S_CLASS',
    "/hit-and-run": 'S_CLASS',
    "/home-afford": 'S_CLASS',
    "/hotel-injury": 'S_CLASS',
    "/hsa": 'S_CLASS',
    "/hud-housing": 'S_CLASS',
    "/hurricane-insurance": 'S_CLASS',
    "/hvac-insurance": 'S_CLASS',
    "/inheritance": 'S_CLASS',
    "/invokana": 'S_CLASS',
    "/ivc-filter": 'S_CLASS',
    "/jet-ski": 'S_CLASS',
    "/jewelry-insurance": 'S_CLASS',
    "/knee-implant": 'S_CLASS',
    "/landscaping-insurance": 'S_CLASS',
    "/lead-poisoning": 'S_CLASS',
    "/lemon-law": 'S_CLASS',
    "/life-insurance": 'S_CLASS',
    "/liheap": 'S_CLASS',
    "/llc-tax": 'S_CLASS',
    "/ltd": 'S_CLASS',
    "/lung-disease": 'S_CLASS',
    "/lupron": 'S_CLASS',
    "/malpractice": 'S_CLASS',
    "/manufactured-home-insurance": 'S_CLASS',
    "/medicaid": 'S_CLASS',
    "/medicare-part-b": 'S_CLASS',
    "/medicare-part-d": 'S_CLASS',
    "/medicare-premium": 'S_CLASS',
    "/mesothelioma": 'S_CLASS',
    "/metal-hip": 'S_CLASS',
    "/mining-injury": 'S_CLASS',
    "/mirena": 'S_CLASS',
    "/mobile-home-insurance": 'S_CLASS',
    "/motorcycle-accident": 'S_CLASS',
    "/ovulation": 'S_CLASS',
    "/scientific": 'S_CLASS',
    "/square-footage": 'S_CLASS',
    "/percentage": 'S_CLASS',
    "/gpa": 'S_CLASS',
    "/age": 'S_CLASS',
    "/loan": 'S_CLASS',
    "/pregnancy": 'S_CLASS',
    "/grade": 'S_CLASS',
    "/compound-interest": 'S_CLASS',
    "/due-date": 'S_CLASS',
    "/salary": 'S_CLASS',
    "/body-fat": 'S_CLASS',
    "/time-calculator": 'S_CLASS'
};

/**
 * Global Shell Resolver
 * Determines the layout ownership for a given pathname.
 */
export function getLayoutShellType(pathname: string | null): LayoutShellType {
    if (!pathname) return 'LEGACY';

    // V5.0 Path Normalization: Standardize lowercase and trim trailing slash
    // Ensures consistent matching regardless of browser or Next.js quirks
    const cleanPath = pathname.toLowerCase().split('?')[0].replace(/\/$/, "");
    const normalizedPath = cleanPath === "" ? "/" : cleanPath;

    // V5.0 Wildcard Resolver:
    // Any path starting with a registered S-Class root is 100% S-Class territory.
    for (const [route, type] of Object.entries(LAYOUT_CONFIG)) {
        const normalizedRoute = route.toLowerCase().replace(/\/$/, "");

        // Exact match or sub-path match (e.g., /mortgage or /mortgage/calculator)
        if (normalizedPath === normalizedRoute || normalizedPath.startsWith(normalizedRoute + "/")) {
            return type;
        }
    }

    return 'LEGACY';
}




